import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Result} from "../types"

//https://www.themuse.com/developers/api/v2
export const getStaticProps: GetStaticProps = async (context) => {
  const API = "https://www.themuse.com/api/public/jobs";
  const res = await fetch(API + '?category=Software%20Engineering&location=Seattle%2C%20WA&page=3&api_key=' +
   process.env.THE_MUSE)
  const jobs = await res.json();
  const {id, contents} = jobs.results[0];
  console.log(contents)
  return {
    props: {
      jobs: jobs
    }
  }
}

// async function statusCheck(res: object) {
//   if (!res.ok}) {
//     throw new Error(await res.text());
//   }
//   return res;
// }


const Home: NextPage = ({jobs}: any) => { //here
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {jobs.results.map((job: any) => { //here
        return <li key={job.id}>{job.contents}</li>
      })}
    </div>
  )
}

export default Home
