import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = ({jobs}: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      {JSON.stringify(jobs)}
=======

      <p className="text-green-900">paragraph</p>
>>>>>>> 05be240f697a9b663679a51d17ceb312803a43d6
    </div>
  )
}

//https://www.themuse.com/developers/api/v2
export const getStaticProps: GetStaticProps = async (context) => {
  const museApi = "https://www.themuse.com/api/public";
  let res = await fetch(museApi + "/jobs?category=Software%20Engineering&location=Seattle%2C%20WA&page=3&api_key=" + process.env.THE_MUSE);
  const jobs = await res.json();
  return {
    props: {
      jobs: jobs,
    }
  }
}

export default Home
